import express from "express";import dotenv from "dotenv";dotenv.config();
const app=express();app.use(express.json());app.use(express.static("public"));
const PORT=Number(process.env.PORT||3000),origins=["REC","MCZ","JPA"],dates=["2026-12-20","2026-12-21","2026-12-22"];
const airlines={AD:"Azul",G3:"GOL",LA:"LATAM"};let intervalMinutes=[30,60].includes(Number(process.env.RADAR_INTERVAL_MINUTES))?Number(process.env.RADAR_INTERVAL_MINUTES):30,priceAlert=Number(process.env.PRICE_ALERT||800),timer=null,lastRun=null,latest=[];
async function query(date){if(!process.env.SERPAPI_KEY)throw Error("SERPAPI_KEY não configurada.");let p=new URLSearchParams({engine:"google_flights",api_key:process.env.SERPAPI_KEY,departure_id:origins.join(","),arrival_id:"UDI",outbound_date:date,type:"2",adults:"1",currency:"BRL",hl:"pt",gl:"br",sort_by:"2",show_hidden:"true"});let r=await fetch("https://serpapi.com/search.json?"+p),j=await r.json();if(!r.ok||j.error)throw Error(j.error||`SerpApi HTTP ${r.status}`);return [...(j.best_flights||[]),...(j.other_flights||[])].map(x=>{let f=x.flights||[],a=f[0]||{},z=f[f.length-1]||{};return{origin:a.departure_airport?.id||"?",destination:z.arrival_airport?.id||"UDI",date,airline:a.airline||"Outra",price:Number(x.price||0),stops:Math.max(0,f.length-1),departure:a.departure_airport?.time||"",arrival:z.arrival_airport?.time||"",collectedAt:new Date().toISOString()}}).filter(x=>origins.includes(x.origin)&&x.destination==="UDI"&&x.price>0)}
async function run(){let out=[];for(let d of dates){try{out.push(...await query(d))}catch(e){out.push({origin:"*",destination:"UDI",date:d,airline:"ERRO",price:0,error:e.message})}}out.sort((a,b)=>a.price-b.price);latest=out;lastRun=new Date().toISOString();return out}
function schedule(){if(timer)clearInterval(timer);timer=setInterval(()=>run().catch(console.error),intervalMinutes*60000)}
app.get("/api/status",(q,s)=>s.json({intervalMinutes,priceAlert,lastRun,running:!!timer,best:latest.find(x=>x.price>0)||null,count:latest.filter(x=>x.price>0).length}));
app.get("/api/results",(q,s)=>s.json({results:latest,lastRun,priceAlert}));
app.post("/api/config",(q,s)=>{let n=Number(q.body?.intervalMinutes),p=Number(q.body?.priceAlert);if(![30,60].includes(n))return s.status(400).json({error:"Intervalo deve ser 30 ou 60 minutos."});if(!Number.isFinite(p)||p<0)return s.status(400).json({error:"Preço-alvo inválido."});intervalMinutes=n;priceAlert=p;schedule();s.json({intervalMinutes,priceAlert})});
app.post("/api/run",async(q,s)=>{try{s.json({results:await run(),lastRun})}catch(e){s.status(500).json({error:e.message})}});
app.listen(PORT,()=>{schedule();console.log(`Radar UDI em http://localhost:${PORT}`);run().catch(console.error)});
